# Generated by Django 5.0.4 on 2024-04-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_base_category_delete_music_base_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Base',
            new_name='Music',
        ),
    ]
