# Generated by Django 5.0.4 on 2024-04-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_rename_base_music'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Article',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at', 'title', 'category'], 'verbose_name': 'Статья по теме', 'verbose_name_plural': 'Статьи по теме'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
