# Generated by Django 5.0.4 on 2024-04-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_remove_article_genre_movie_music_videogame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
    ]
