# Generated by Django 5.0.4 on 2024-05-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_remove_article_genre_alter_article_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='genre',
        ),
    ]
